version: "3.8"

services:
  postgres:
    image: postgres:14.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=x-state-proto
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 15
